FROM node:18-alpine

WORKDIR /code

COPY package.json /code/package.json
COPY yarn.lock /code/yarn.lock

COPY . /code

RUN cp src/config/parameters/production.env .env
RUN yarn install

CMD ["tail", "-f", "/dev/null"]
